---

- hosts: all
  become: true
  tasks:

  - name: install apache2 package
    apt: 
      name: apache2
      state: latest
  
  - name: add apache2 php lib
    apt:
      name: libapach2-mod-php
      state: latest
